---
- name: install web components
  yum: name={{item}} state=latest
  with_items:
    - httpd
    - mod_wsgi-python27

- name: ensure mod_wsgi enabled
  apache2_module: state=present name=wsgi
  notify: restart httpd

- name: ensure httpd started
  service: name=httpd state=started enabled=yes
