version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Ansible
          command: |
            pip install ansible
      - run:
          name: Run ansible-playbook site.yml -i environments/dev
          command: |
            echo $lpgKey.pem > lpgKey.pem
            echo $vaultpass > vault.yml
            cat lpgKey.pem
            chmod 400 lpgKey.pem
            ansible-playbook site.yml -i environments/dev

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

