version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Ansible
          command: |
            pip install ansible
      - run:
          name: Run ansible-playbook site.yml -i environments/dev
          command: |
            ls -la  ~/.ssh/
            echo $vaultpass > vault.yml
            ansible-playbook site.yml -i environments/dev

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

