---
- name: Install unzip
  apt:
    name: unzip
    state: present

- name: Make vault directories
  file:
    path: "/opt/{{ item }}"
    owner: root
    group: root
    mode: 0755
    recurse: no
    state: directory
  with_items: ["vault/bin", "vault/config", "vault/data"]
  tags: dir

#- name: copy acl.json
#  template: src=acl.json.j2 dest=/opt/vault/config/acl.json
#  notify: reload vault
#
#- name: copy config.json
#  template: src=config.json.j2 dest=/opt/vault/config/config.json
#  notify: reload vault

- name: copy vault.service
  copy: src=vault.service dest=/etc/systemd/system/vault.service mode=0540
  notify: reload vault

- name: Install vault
  shell: |
    version="{{ vaultVersion }}"
    wget https://releases.hashicorp.com/vault/{{ vaultVersion }}/vault_{{ vaultVersion }}_linux_amd64.zip -O /opt/vault/bin/vault_{{ vaultVersion }}_linux_amd64.zip
    cd /opt/vault/bin/
    unzip /opt/vault/bin/vault_{{ vaultVersion }}_linux_amd64.zip
    rm /opt/vault/bin/vault_{{ vaultVersion }}_linux_amd64.zip
    ln -s /opt/vault/bin/vault /opt/vault/bin/vault_{{ vaultVersion }}
  args:
    creates: /opt/vault/bin/vault_{{ vaultVersion }}
  notify: restart vault

- name: Ensure vault started
  service: name=vault state=started

