---

- name: dgraphServer
  docker_container:
    name: dgraphServer
    image: dgraph/dgraph
    state: started
    recreate: no
    command: "{{ serverCommand }}"
    published_ports:
      - "{{port}}:{{port}}"
      - 8080:8080
    volumes:
      - /datadisk/dgraph:/dgraph
      - /etc/hosts.ansible:/etc/hosts
  become: yes
  tags: dgraphServer
