---
- name: Install pip
  apt:
    name: python-pip
    state: present
    update_cache: no
  tags : docker

- name: Install Docker
  shell: |
    wget https://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/amd64/docker-ce_17.03.2~ce-0~ubuntu-xenial_amd64.deb
    sudo apt-get install libltdl7
    sudo dpkg -i docker-ce_17.03.2~ce-0~ubuntu-xenial_amd64.deb
  args:
    creates: /usr/bin/docker
  tags : docker

- pip:
    name: docker-py
  tags : docker

- name: Ensure docker started
  service: name=docker state=started
  tags : docker






