---
- name: Install Docker
  shell: |
    wget https://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/amd64/docker-ce_17.03.2~ce-0~ubuntu-xenial_amd64.deb
    sudo dpkg -i docker-ce_17.03.2~ce-0~ubuntu-xenial_amd64.deb
  args:
    creates: /usr/bin/docker

- name: Install docker python
  shell: |
    pip install docker-py
  args:
    creates: /usr/local/lib/python2.7/dist-packages/docker

- name: Ensure docker started
  service: name=docker state=started







