---
- name: Include variables
  include_vars:
    dir: '/home/circleci/project/environments/{{ env }}/group_vars/tokens/'
  tags: httpd

- name: Run httpd container
  docker_container:
    name: httpd
    image: httpd
    state: started
    recreate: no
    exposed_ports:
      - 80
    volumes:
      - /tmp:/usr/local/apache2/htdocs/
    env:
        consulToken: "{{ consulToken }}"
        consulServer: "{{ groups.services [0] }}"
        tokenName: "{{ tokenName }}"
        VIRTUAL_HOST: www.123.com
  become: yes
  tags: httpd

- name: Run httpd container 2
  docker_container:
    name: httpd2
    image: httpd
    state: started
    recreate: no
    exposed_ports:
      - 80
    volumes:
      - /tmp/2:/usr/local/apache2/htdocs/
    env:
        consulToken: "{{ consulToken }}"
        consulServer: "{{ groups.services [0] }}"
        tokenName: "{{ tokenName }}"
        VIRTUAL_HOST: www.123.com
        NewVarable: blahBlah

  become: yes
  tags: httpd


#http://docs.ansible.com/ansible/latest/docker_container_module.html#docker-container